import { type PropsWithChildren } from 'react'

import type { Metadata } from 'next'
import { Golos_Text } from 'next/font/google'

import './globals.css'

const golos = Golos_Text({
	subsets: ['latin'],
	variable: '--font-tolos',
	weight: ['400', '500', '600', '700', '800'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html
			lang="en"
			className={golos.variable}
		>
			<body>{children}</body>
		</html>
	)
}
