import { render } from '@react-email/render';
import type { BasePayload, TextField } from 'payload';

import NewArticleEmail from '@/emails/NewArticleEmail';
import toyzConfig from '@/toyzConfig';
import extractLexicalText from '@/utils/extractLexicalText';

// Resend's free tier allows ~2 requests/sec. Spacing emails 600ms apart keeps
// us safely under that ceiling without batching.
const RESEND_INTER_EMAIL_DELAY_MS = 600;

// When Resend responds with HTTP 429 (rate-limited), wait a full second before
// retrying that single email once. This is shorter than a job retry and keeps
// the dispatch progressing instead of bailing on the first throttle.
const RESEND_RATE_LIMIT_RETRY_DELAY_MS = 1000;

// Number of sentences pulled from the article body to act as the email
// preview/summary block.
const EMAIL_SUMMARY_SENTENCE_COUNT = 2;

const CDN_BASE_URL = 'https://cdn.toyzwebzine.com';

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const inputSchema: TextField[] = [
  { name: 'dispatchId', type: 'text', required: true },
];

/**
 * Resolves the image URL to embed in the newsletter email.
 *
 * Prefers the `email` size variant generated by the Media collection, falling
 * back to the original filename. Image fetch failures are intentionally
 * swallowed — the email is sent without an image rather than failing the
 * entire dispatch over a missing thumbnail.
 */
const buildArticleImageUrl = async (
  payload: BasePayload,
  imagesField: unknown
): Promise<string> => {
  if (!imagesField) {
    return '';
  }

  const mediaId =
    typeof imagesField === 'object'
      ? (imagesField as { id: string | number }).id
      : imagesField;

  if (!mediaId) {
    return '';
  }

  try {
    const media = await payload.findByID({
      collection: 'media',
      id: mediaId as string | number,
    });

    if (!media) {
      return '';
    }

    const emailSize = (media as { sizes?: { email?: { filename?: string } } }).sizes?.email;

    if (emailSize?.filename) {
      return `${CDN_BASE_URL}/${emailSize.filename}`;
    }

    const filename = (media as { filename?: string }).filename;

    if (filename) {
      return `${CDN_BASE_URL}/${filename}`;
    }
  } catch {
    // Image lookup is non-critical — fall through and return empty string.
  }

  return '';
};

/**
 * Sends a newsletter to all active subscribers for a single dispatch record.
 *
 * Idempotency strategy:
 *   - The dispatch row is the source of truth. We mark it `sending`, then
 *     stream emails one at a time, recording each successful recipient in
 *     `sentSubscribers`. If the task crashes and Payload retries, we resume
 *     from `sentSubscribers` — nobody gets a duplicate, nobody is skipped.
 *   - The hook that created this dispatch already enforced "only one dispatch
 *     per article" via a unique index. This task never re-derives that
 *     decision; it just executes the existing dispatch.
 */
export const dispatchNewsletterTask = {
  slug: 'dispatchNewsletter',
  retries: 3,
  inputSchema,
  handler: async ({
    input,
    req,
  }: {
    input: { dispatchId: string };
    req: { payload: BasePayload };
  }) => {
    const { payload } = req;
    const { dispatchId } = input;

    const dispatch = await payload.findByID({
      collection: 'newsletter-dispatches',
      id: dispatchId,
    });

    if (!dispatch) {
      payload.logger.warn(`📭 Dispatch ${dispatchId} not found — skipping.`);
      return { output: {} };
    }

    // Only `queued` (first run) and `sending` (retry resume) are actionable.
    // `sent`, `disabled`, `failed` are terminal and must not re-trigger emails.
    const isActionable = dispatch.status === 'queued' || dispatch.status === 'sending';

    if (!isActionable) {
      payload.logger.info(
        `⏭️ Dispatch ${dispatchId} status is "${dispatch.status}" — skipping (not in actionable state).`
      );
      return { output: {} };
    }

    if (dispatch.status === 'queued') {
      await payload.update({
        collection: 'newsletter-dispatches',
        id: dispatchId,
        data: {
          status: 'sending',
          triggeredAt: new Date().toISOString(),
        },
      });
    }

    const articleId =
      typeof dispatch.article === 'object' ? dispatch.article.id : dispatch.article;

    if (!articleId) {
      await payload.update({
        collection: 'newsletter-dispatches',
        id: dispatchId,
        data: {
          status: 'failed',
          lastError: 'Article reference missing',
        },
      });
      return { output: {} };
    }

    // Track which subscriber IDs already received this email in a prior run
    // (Payload retries reuse the same dispatch row).
    const alreadySentSubscriberIds = new Set(
      (dispatch.sentSubscribers ?? [])
        .map((subscriber) => (typeof subscriber === 'object' ? subscriber.id : subscriber))
        .map((id) => String(id))
    );

    const { docs: subscribers } = await payload.find({
      collection: 'subscribers',
      where: { isActive: { equals: true } },
      limit: 0,
    });

    if (!subscribers.length) {
      await payload.update({
        collection: 'newsletter-dispatches',
        id: dispatchId,
        data: {
          status: 'sent',
          recipientCount: 0,
          completedAt: new Date().toISOString(),
        },
      });
      payload.logger.info(`ℹ️ Dispatch ${dispatchId} had no active subscribers.`);
      return { output: {} };
    }

    await payload.update({
      collection: 'newsletter-dispatches',
      id: dispatchId,
      data: { recipientCount: subscribers.length },
    });

    let successCount = Number(dispatch.successCount ?? 0);
    let failureCount = Number(dispatch.failureCount ?? 0);
    const nextSentSubscribers: (string | number)[] = Array.from(alreadySentSubscriberIds);
    let lastError: string | undefined;

    // If the article gets unpublished mid-dispatch we abort the whole run and
    // mark the dispatch `disabled`. Tracked outside the loop so the post-loop
    // finalizer knows which terminal state to write.
    let articleNoLongerPublished = false;

    for (const subscriber of subscribers) {
      const subscriberId = String(subscriber.id);

      if (alreadySentSubscriberIds.has(subscriberId)) {
        continue;
      }

      const locale: 'en' | 'tr' = subscriber.preferredLocale === 'tr' ? 'tr' : 'en';

      let article;

      try {
        article = await payload.findByID({
          collection: 'articles',
          id: articleId,
          locale,
        });
      } catch (error) {
        lastError = error instanceof Error ? error.message : String(error);
        failureCount += 1;
        continue;
      }

      if (!article || article._status !== 'published') {
        articleNoLongerPublished = true;
        break;
      }

      if (!article.slug) {
        failureCount += 1;
        lastError = `Article ${articleId} missing slug for locale ${locale}`;
        continue;
      }

      const summary = extractLexicalText(article.content, EMAIL_SUMMARY_SENTENCE_COUNT);
      const imageUrl = await buildArticleImageUrl(payload, article.images);
      const articleUrl = `${toyzConfig.baseUrl}/${locale}/content/${article.slug}`;
      const unsubscribeUrl = `${toyzConfig.baseUrl}/api/subscribers/unsubscribe?email=${subscriber.email}`;

      const html = await render(
        <NewArticleEmail
          title={article.title}
          summary={summary}
          imageUrl={imageUrl}
          articleUrl={articleUrl}
          unsubscribeUrl={unsubscribeUrl}
          locale={locale}
        />
      );

      const subject =
        locale === 'tr' ? `Yeni İçerik: ${article.title}` : `New Content: ${article.title}`;

      try {
        await payload.sendEmail({ to: subscriber.email, subject, html });
        successCount += 1;
        nextSentSubscribers.push(subscriber.id);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        const isRateLimited = message.includes('429');

        if (isRateLimited) {
          await sleep(RESEND_RATE_LIMIT_RETRY_DELAY_MS);

          try {
            await payload.sendEmail({ to: subscriber.email, subject, html });
            successCount += 1;
            nextSentSubscribers.push(subscriber.id);
          } catch (retryError) {
            failureCount += 1;
            lastError = retryError instanceof Error ? retryError.message : String(retryError);
          }
        } else {
          failureCount += 1;
          lastError = message;
        }
      }

      await sleep(RESEND_INTER_EMAIL_DELAY_MS);
    }

    if (articleNoLongerPublished) {
      await payload.update({
        collection: 'newsletter-dispatches',
        id: dispatchId,
        data: {
          status: 'disabled',
          successCount,
          failureCount,
          sentSubscribers: nextSentSubscribers as never,
          lastError: 'Article no longer published when dispatch ran',
          completedAt: new Date().toISOString(),
        },
      });

      payload.logger.warn(
        `🛑 Dispatch ${dispatchId} disabled because article ${articleId} is not published.`
      );

      return { output: {} };
    }

    const everyRecipientFailed =
      successCount === 0 && failureCount === subscribers.length;
    const finalStatus = everyRecipientFailed ? 'failed' : 'sent';

    await payload.update({
      collection: 'newsletter-dispatches',
      id: dispatchId,
      data: {
        status: finalStatus,
        successCount,
        failureCount,
        sentSubscribers: nextSentSubscribers as never,
        lastError,
        completedAt: new Date().toISOString(),
      },
    });

    payload.logger.info(
      `✅ Dispatch ${dispatchId} finished: status=${finalStatus}, success=${successCount}, failure=${failureCount}.`
    );

    return { output: {} };
  },
};
